### ISSUE TITLE
TypeError: data.forEach is not a function

### ISSUE THREAD

**Issue by RossComputerGuy** [santigimeno/node-x11-prop#6]
```
/home/spaceboyross/RDE/src/panel/node_modules/x11-prop/lib/encoder.js:29
            data.forEach(function(el, index) {
                 ^

TypeError: data.forEach is not a function
    at Object.exports.encode (/home/spaceboyross/RDE/src/panel/node_modules/x11-prop/lib/encoder.js:29:18)
    at _set_property (/home/spaceboyross/RDE/src/panel/node_modules/x11-prop/lib/set_prop.js:55:32)
    at /home/spaceboyross/RDE/src/panel/node_modules/x11-prop/lib/set_prop.js:48:13
    at /home/spaceboyross/RDE/src/panel/node_modules/x11-prop/node_modules/async/lib/async.js:254:17
    at done (/home/spaceboyross/RDE/src/panel/node_modules/x11-prop/node_modules/async/lib/async.js:135:19)
    at /home/spaceboyross/RDE/src/panel/node_modules/x11-prop/node_modules/async/lib/async.js:32:16
    at /home/spaceboyross/RDE/src/panel/node_modules/x11-prop/node_modules/async/lib/async.js:251:21
    at /home/spaceboyross/RDE/src/panel/node_modules/x11-prop/node_modules/async/lib/async.js:575:34
    at ReadFixedRequest.callback (/home/spaceboyross/RDE/src/panel/node_modules/x11/lib/xcore.js:545:21)
    at ReadFixedRequest.execute (/home/spaceboyross/RDE/src/panel/node_modules/x11/lib/unpackstream.js:41:10)
```

**Comment by santigimeno** [comment]
Hi, can you post a reproducible test case?

**Comment by RossComputerGuy** [comment]
I fixed it
